version: 2

plugins:

  phpcodesniffer:
    enabled: true

  sonar-php:
    enabled: true
    config:
      tests_patterns:
        - tests/**

exclude_patterns:
  - build/
  - config/
  - demo/
  - docs/
  - lexemes/
